rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - rbx
  - jruby
env:
  - JRUBY_OPTS="-Xcext.enabled=true"
notifications:
  recipients:
    - test-unit-commit@googlegroups.com
# matrix:
#   allow_failures:
#     - rvm: rbx
before_install:
  - gem update bundler
