rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
  - rbx
  - jruby
env:
  - JRUBY_OPTS="-Xcext.enabled=true"
notifications:
  webhooks:
    - https://webhook.commit-email.info/
# matrix:
#   allow_failures:
#     - rvm: rbx
before_install:
  - gem update bundler
